### PR TITLE
Fix CI failure in linux

### PR DESCRIPTION
**Pull request by sumleo**
I am trying to work on CI for HiQ. However, some failures have been occurred during the CI process.
Could you please help me to do the code review?

### CODE REVIEW

**Comment by sumleo** [comment]
The failure log lies here: https://travis-ci.com/github/sumleo/HiQsimulator/builds/178551776

**Comment by sumleo** [comment]
Currently, it works.(see  https://github.com/sumleo/HiQsimulator/runs/952271693 )

**Comment by DechinPhy** [comment]
@i2000s @Takishima @yzotov Could you please take a review on this PR? It seems the only only change are some additional settings.

**Comment by Takishima** [comment]
This will all be fixed when we publish the latest changes which removes the `Feature` class entirely from the `setup.py` file. These changes should be published sometime this week.

I am therefore closing this PR.

**Pull request closed without merging**
