### PR TITLE
Fix indentation + add unit testing (partial) + introduce XSIMD library for broader intrinsics support

### PR DESCRIPTION
**Pull request by Takishima**
The main purpose of this PR is to introduce broader support for compiler intrinsics by making use of the XSIMD library. As a fallback option for people without the library or when compiling code without sufficient intrinsics support, a XSIMD fallback library is also implemented.

This PR also introduces the use of Boost.Test for unit testing for some components.

### CODE REVIEW

**Comment by i2000s** [comment]
Good job! BTW, do you think we can benefit from LLVM compilers?

**Comment by Takishima** [comment]
> Good job! BTW, do you think we can benefit from LLVM compilers?

Short answer: maybe.

Somewhat longer answer: technically, the code should be compiler agnostic to a large extent, so in order to see the benefits (if any) of using LLVM compilers would require some analysis of the generated assembly code of some known function or rely on measuring the runtime performance of code compiled on GCC/LLVM/MSVC for example.

**Comment by i2000s** [comment]
Just a style request: could you commit with specific information of fixes for the solved problems? Of course, it doesn't matter for minor fixes.

You can do a squash when you merge the PR to hide unnecessary commit information. Thanx for the good work!

**Comment by Takishima** [comment]
@i2000s Those are mostly minor adjustments that I intended to squash into their respective initial commits, which is the reason why I did them like that. 

I will otherwise always make proper commit messages.

**Comment by Takishima** [comment]
So for now, the Mac OSX build is allowed to fail because running the examples scripts fails for some weird reason.
I think this is due to the fact that the import of the `hiq` module fails but I cannot seem to reproduce this on my own machine. I'll open an issue in case somebody wants to investigate this further.

**Pull request merged**
